/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Hazard = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'hazardType' : IDL.Text,
  'timestamp' : Time,
  'severity' : IDL.Text,
  'location' : IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  }),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'handle' : IDL.Opt(IDL.Text),
});
export const EmergencyContact = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
});
export const SOSStatus = IDL.Variant({
  'active' : IDL.Null,
  'sent' : IDL.Null,
  'ended' : IDL.Null,
  'queued' : IDL.Null,
});
export const Breadcrumb = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const SOSEventView = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : SOSStatus,
  'endTime' : IDL.Opt(Time),
  'userId' : IDL.Principal,
  'note' : IDL.Text,
  'breadcrumbs' : IDL.Vec(Breadcrumb),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBreadcrumb' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'endSOS' : IDL.Func([IDL.Nat], [], []),
  'getAllHazards' : IDL.Func([], [IDL.Vec(Hazard)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmergencyContacts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getNearbyHazards' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(Hazard)],
      ['query'],
    ),
  'getSOSByStatus' : IDL.Func([SOSStatus], [IDL.Vec(SOSEventView)], ['query']),
  'getSOSStatus' : IDL.Func([IDL.Nat], [SOSEventView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSOS' : IDL.Func([IDL.Principal], [IDL.Vec(SOSEventView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmergencyContacts' : IDL.Func([IDL.Vec(EmergencyContact)], [], []),
  'startSOS' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitHazard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Record({
          'latitude' : IDL.Float64,
          'longitude' : IDL.Float64,
          'timestamp' : Time,
        }),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Hazard = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'hazardType' : IDL.Text,
    'timestamp' : Time,
    'severity' : IDL.Text,
    'location' : IDL.Record({
      'latitude' : IDL.Float64,
      'longitude' : IDL.Float64,
      'timestamp' : Time,
    }),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'handle' : IDL.Opt(IDL.Text),
  });
  const EmergencyContact = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
  });
  const SOSStatus = IDL.Variant({
    'active' : IDL.Null,
    'sent' : IDL.Null,
    'ended' : IDL.Null,
    'queued' : IDL.Null,
  });
  const Breadcrumb = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const SOSEventView = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : SOSStatus,
    'endTime' : IDL.Opt(Time),
    'userId' : IDL.Principal,
    'note' : IDL.Text,
    'breadcrumbs' : IDL.Vec(Breadcrumb),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBreadcrumb' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'endSOS' : IDL.Func([IDL.Nat], [], []),
    'getAllHazards' : IDL.Func([], [IDL.Vec(Hazard)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getNearbyHazards' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(Hazard)],
        ['query'],
      ),
    'getSOSByStatus' : IDL.Func(
        [SOSStatus],
        [IDL.Vec(SOSEventView)],
        ['query'],
      ),
    'getSOSStatus' : IDL.Func([IDL.Nat], [SOSEventView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSOS' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SOSEventView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmergencyContacts' : IDL.Func([IDL.Vec(EmergencyContact)], [], []),
    'startSOS' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitHazard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Record({
            'latitude' : IDL.Float64,
            'longitude' : IDL.Float64,
            'timestamp' : Time,
          }),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };