/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Breadcrumb {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Time,
}
export interface EmergencyContact {
  'id' : bigint,
  'contactInfo' : string,
  'relationship' : string,
  'name' : string,
}
export interface Hazard {
  'id' : bigint,
  'description' : string,
  'hazardType' : string,
  'timestamp' : Time,
  'severity' : string,
  'location' : {
    'latitude' : number,
    'longitude' : number,
    'timestamp' : Time,
  },
}
export interface SOSEventView {
  'id' : bigint,
  'startTime' : Time,
  'status' : SOSStatus,
  'endTime' : [] | [Time],
  'userId' : Principal,
  'note' : string,
  'breadcrumbs' : Array<Breadcrumb>,
}
export type SOSStatus = { 'active' : null } |
  { 'sent' : null } |
  { 'ended' : null } |
  { 'queued' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'handle' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBreadcrumb' : ActorMethod<[bigint, number, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'endSOS' : ActorMethod<[bigint], undefined>,
  'getAllHazards' : ActorMethod<[], Array<Hazard>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmergencyContacts' : ActorMethod<[Principal], Array<EmergencyContact>>,
  'getNearbyHazards' : ActorMethod<[number, number, number], Array<Hazard>>,
  'getSOSByStatus' : ActorMethod<[SOSStatus], Array<SOSEventView>>,
  'getSOSStatus' : ActorMethod<[bigint], SOSEventView>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSOS' : ActorMethod<[Principal], Array<SOSEventView>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmergencyContacts' : ActorMethod<[Array<EmergencyContact>], undefined>,
  'startSOS' : ActorMethod<[string], bigint>,
  'submitHazard' : ActorMethod<
    [
      string,
      string,
      string,
      { 'latitude' : number, 'longitude' : number, 'timestamp' : Time },
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];